api/urls.py
from django.urls import path, include
from .views import *



urlpatterns = [
     path('bot-users', BotUserCreateView.as_view()),
     path('feedbacks', FeedbackCreateView.as_view()),
     path('courses', CourseListView.as_view()),
     path('attendances', AttendanceListView.as_view()),
     path('payments', AddCashToWalletListView.as_view()),
     path('students', StudentListview.as_view()),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('income/', include('payment.urls')),
    path('users/', include('users.urls')),
    path('api/v1/', include('api.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/models.py
from django.db import models

# Create your models here.
class BotUsers(models.Model):
      name = models.CharField(max_length=100, null=True, blank=True)
      username = models.CharField(max_length=100, null=True, blank=True)
      chat_id = models.PositiveBigIntegerField(null=True, blank=True)
      
      def __str__(self):
            return str(self.name)

class Feedback(models.Model):
      name = models.CharField(max_length=120)
      body = models.TextField()
      
      def __str__(self):
            return str(self.name)
                  

course/models.py
from random import choices
from django.db import models
from users.models import User
from datetime import date
from django.utils import timezone
import random
from .validators import validate_grade, validate_phone_number
from django.db.models import Sum

# Create your models here.
times = (
    ('1', '7.30:9.30'),
    ('2', '10.00:12:00'),
    ('3', '13.00:15.00'),
    ('4', '15.30:17.30'),
)
days = (
    ('1', 'Dush-Chor-Jum'),
    ('2', 'Sesh-Pay-Shan')
)

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=120)
    wallet = models.IntegerField(default=0)
    token_id = models.CharField(default=str(random.randint(10000000, 99999999)), max_length=150, unique=True)
    image = models.ImageField(upload_to='students/', blank=True, null=True)

    def __str__(self):
        return str(self.full_name)

    @staticmethod
    def get_wallet_sums():

        negative_wallet_sum = Student.objects.filter(wallet__lt=0).aggregate(Sum('wallet'))['wallet__sum'] or 0
        positive_wallet_sum = Student.objects.filter(wallet__gt=0).aggregate(Sum('wallet'))['wallet__sum'] or 0
        return negative_wallet_sum, positive_wallet_sum

class Course_for_news(models.Model):
    name = models.CharField(max_length=200, default="kurs nomini kiriting")

    def __str__(self):
        return self.name


class Receiption(models.Model):

    full_name = models.CharField(max_length=200)
    phone_number = models.CharField(
        max_length=13,
        validators=[validate_phone_number],
        help_text="Raqam faqat +998 dan boshlanib 9 ta raqamdan tashkil topishi lozim misol uchun: +998991234567"
    )
    course = models.ForeignKey(Course_for_news, on_delete=models.CASCADE)
    created_at = models.DateField(default=date.today())
    status = models.BooleanField(default=False)

    def __str__(self):
        return (f"{self.full_name}"
                f"{self.course}"
                f"{self.phone_number} "
                f"{self.status} "
                f"{self.created_at}")

#yangi
class ReceiptionAdmin(models.Model):

    name = models.CharField(max_length=200)
    phone_number = models.CharField(
        max_length=13,
        validators=[validate_phone_number],
        help_text="Raqam faqat +998 dan boshlanib 9 ta raqamdan tashkil topishi lozim misol uchun: +998991234567"
    )
    course = models.ForeignKey(Course_for_news, on_delete=models.CASCADE)
    created_at = models.DateField(default=date.today())
    status = models.BooleanField(default=False)

    def __str__(self):
        return (f"{self.full_name}"
                f"{self.course}"
                f"{self.phone_number} "
                f"{self.status} "
                f"{self.created_at}")


class Course(models.Model):
    name = models.CharField(max_length=120)
    teacher = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.TextField(null=True, blank=True)
    price = models.PositiveBigIntegerField()
    students = models.ManyToManyField(Student)
    time = models.CharField(max_length=150)
    days = models.CharField(max_length=150, choices=days)
    room = models.PositiveBigIntegerField()
    start_date = models.DateField(default=date.today(), blank=True, null=True)
    end_date = models.DateField(null=True, blank=True)
    is_ended = models.BooleanField(default=False)

    def __str__(self):
        return (f"{self.name} "
                f"{self.teacher} "
                f"{self.title} "
                f"{self.price} "
                f"{self.students}"
                f"{self.time} "
                f"{self.days} "
                f"{self.room}")

class AttendanceGroup(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    time = models.CharField(max_length=150, choices=times)
    date = models.DateField(default=date.today())
    teacher = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=150)

    def __str__(self):
        return str(self.status)


class Attendance(models.Model):
    attendance = models.ForeignKey(AttendanceGroup, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    date = models.DateField(default=date.today())
    present = models.BooleanField(default=True)
    STATUS_CHOICES = [
        ('sababli', 'sababli'),
        ('sababsiz', 'sababsiz'),
        ('kelgan', 'kelgan')
    ]
    status = models.CharField(max_length=150, choices=STATUS_CHOICES, default='kelgan', blank=True, null=True)

    def __str__(self):
        return str(self.student) + " " + str(self.present)


class Task(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, limit_choices_to={'is_teacher': True})
    date = models.DateTimeField(default=timezone.now)
    task_name = models.CharField(max_length=100)
    file = models.FileField(upload_to='tasks/', blank=True, null=True)
    task = models.TextField()
    task_description = models.TextField()
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='Kurs')

    def __str__(self):
        return str(self.task_name) + str(self.owner)


    class Meta:
        ordering = ['-date']


class Grade(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='grades')
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    grade = models.CharField(max_length=5, validators=[validate_grade])

    def __str__(self):
        return f"{self.student.full_name} - {self.task.task_name} - {self.grade}"


class DynamicField(models.Model):
    FIELD_TYPES = [
        ('char', 'CharField'),
        ('int', 'IntegerField'),
        ('choice', 'ChoiceField'),
    ]

    name = models.CharField(max_length=255)
    field_type = models.CharField(max_length=10, choices=FIELD_TYPES)
    choices = models.TextField(blank=True, null=True)  # Used for ChoiceField

    def __str__(self):
        return self.name


class RegistrationData(models.Model):
    # This will store the name of the field and its value as a JSON object
    data = models.JSONField()

    def __str__(self):
        return str(self.data)



class Certificates_example(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    pdf = models.FileField(upload_to='certificates/')

    def __str__(self):
        return str(self.course)


class Certificate(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    pdf = models.FileField(upload_to='certificates/')

    def __str__(self):
        return f'Certificate for {self.student.full_name} - {self.course.name}'



templates/boss/all_courses.html
{% extends 'boss/base.html' %}
{% block title %} Barcha kurslar {% endblock title %}

{% block content %}
<style>
.card {
    border: none;
    overflow-x: auto;
}
</style>
<div class="col-12">
    <div class="page-title-box d-sm-flex align-items-center justify-content-between">
        <button 
            type="button" 
            class="btn btn-lg btn-secondary btn-my-4"
            data-bs-toggle="modal"
            data-bs-target="#createCourseModal"
        >
            Kurs yaratish
        </button>
        <div class="page-title-right">
            <ol class="breadcrumb m-0">
                <li class="breadcrumb-item"><a href="{% url 'income' %}">Kirim</a></li>
                <li class="breadcrumb-item active">Barcha kurslar</li>
            </ol>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="createCourseModal" tabindex="-1" aria-labelledby="createCourseModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="createCourseModalLabel">Kurs yaratish</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <!-- Load the course creation form here -->
          <form method="post" id="createCourseForm" action="{% url 'create-course' %}">
    {% csrf_token %}

        <div id="div_id_name" class="form-group">
            <label for="id_name" class="requiredField">Nomi</label>
            <input type="text" name="name" class="form-control" required>
        </div>

        <div id="div_id_teacher" class="form-group">
            <label for="id_teacher" class="requiredField">O'qituvchi</label>
            <select name="teacher" class="form-select" required>
                {% for user in users %}
                <option value="{{ user.id }}">{{ user.username }}</option>
                {% endfor %}
            </select>
        </div>

        <div id="div_id_title" class="form-group">
            <label for="id_title" class="requiredField">Title</label>
            <input type="text" name="title" class="form-control" required>
        </div>

        <div id="div_id_price" class="form-group">
            <label for="id_price" class="requiredField">Narxi</label>
            <input type="number" name="price" class="form-control" required>
        </div>





        <div id="div_id_days" class="form-group">
            <label for="id_days" class="requiredField">Kunlar</label>
            <select name="days" class="form-select" required>
                {% for value, label in days %}
                <option value="{{ value }}">{{ label }}</option>
                {% endfor %}
            </select>
        </div>

        <div id="div_id_room" class="form-group">
            <label for="id_room" class="requiredField">Xona</label>
            <input type="number" name="room" class="form-control" required>
        </div>
       <div id="div_id_time" class="form-group">
            <label for="id_time" class="requiredField">Time</label>
            <input type="text" name="time" class="form-control" required>
        </div>
        <div class="form-group">
            <label for="student_search">O'quvchilarni izlash:</label>
            <input type="text" id="student_search" class="form-control" placeholder="O'quvchilarni qidiring...">
        </div>

        <div id="student_table" class="table-responsive">
            <table id="datatable-bordered" class="table table-bordered dt-responsive nowrap">
                <thead>
                    <tr>

                        <th scope="col" width="3%">Tanlash</th>
                        <th scope="col">Full Name</th>
                        <th scope="col">Telefon raqami</th>

                    </tr>
                </thead>
                <tbody>
                    {% for student in students %}


                    <tr>
                        <td>
                            <input class="form-check-input custom-checkbox"  type="checkbox" name="students" value="{{ student.id }}" id="student_{{ student.id }}" {% if student in form.instance.students.all %}checked{% endif %}>
                        </td>

                        <td>
                            <label class="form-check-label" for="student_{{ student.id }}">
                                {{ student.full_name }}
                            </label>
                        </td>


                        <td>{{ student.phone_number }}</td>

                    </tr>

                    {% endfor %}
                </tbody>
            </table>
        </div>

        <br>
    <!-- Include other fields similarly -->
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Yopish</button>
        <button type="submit" class="btn btn-primary">Saqlash</button>
    </div>
</form>
          </div>
          </div>
          </div>
</div>

<div class="modal fade" id="editCourseModal" tabindex="-1" aria-labelledby="editCourseModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editCourseModalLabel">Kursni Tahrirlash</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="editCourseModalBody">
        <!-- Modal body will be loaded here via AJAX -->
      </div>
    </div>
  </div>
</div>

<div style="margin-top: 15px;" class="card shadow col-12">
    <div class="card-header d-flex justify-content-between align-items-center">
        <h4 class="card-title">Barcha kurslar</h4>
        <div>
            <a class="btn btn-outline-primary" href="{% url 'courses' %}">Barcha</a>
            <a class="btn btn-outline-success" href="{% url 'ongoing-courses' %}">Davom etayotgan</a>
            <a class="btn btn-outline-danger" href="{% url 'ended-courses' %}">Tugagan</a>
        </div>
    </div>
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Kurs nomi</th>
            <th scope="col">Ustoz</th>
            <th scope="col">Narx</th>
            <th scope="col">Kunlar</th>
            <th scope="col">Smena</th>
            <th scope="col">Xona</th>
            <th scope="col">O'quvchilar soni</th>
            <th scope="col">Ekshin</th>
            <th scope="col">Holati</th>
        </tr>
    </thead>
    <tbody>
        {% for course in courses %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td><a href="{% url 'course_details' course_id=course.id %}">{{ course.name }}</a></td>
            <td>{{ course.teacher }}</td>
            <td>{{ course.price }} so'm</td>
            <td>
                {% if course.days == '1' %}
                Dush-Chor-Jum
                {% else %}
                Sesh-Pay-Shan
                {% endif %}
            </td>
            <td>{{ course.time }}</td>
            <td>{{ course.room }}</td>
            <td>{{ course.students.count }}</td>
            <td><a class="btn btn-danger badge" href="{% url 'edit-course' course.id %}">Tahrirlash</a></td>
            <td>
                {% if course.is_ended %}
                ❌
                {% else %}
                ✅
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

</div>

<script>
document.getElementById('openCreateCourseModal').addEventListener('click', function() {
    fetch("{% url 'create-course' %}")
        .then(response => response.text())
        .then(html => {
            document.getElementById('createCourseModalBody').innerHTML = html;
        })
        .catch(error => console.log('Error loading modal form:', error));
});


document.addEventListener('submit', function(e) {
    if (e.target && e.target.id === 'createCourseForm') {
        e.preventDefault();
        const form = e.target;
        const formData = new FormData(form);

        fetch(form.action, {
            method: 'POST',
            body: formData,
            headers: {
                'X-Requested-With': 'XMLHttpRequest',
            },
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                // Optionally, reload the page or close the modal and update the content dynamically
                $('#createCourseModal').modal('hide');  // Hide the modal using jQuery
                location.reload();  // Reload the page to reflect changes
            } else if (data.errors) {
                const modalBody = document.getElementById('createCourseModalBody');
                modalBody.innerHTML = data.html;  // Re-render the form with errors
            }
        })
        .catch(error => console.error('Error submitting form:', error));
    }
});
</script>
{% endblock content %}

templates/boss/all_payments.html
{% extends 'boss/base.html' %}
{% block title %} Barcha to'lovlar {% endblock title %}

{% block content %}

<div class="col-12">
      <div class="page-title-box d-sm-flex align-items-center justify-content-between">
          <h4 class="mb-sm-0 font-size-18">Barcha to'lovlar </h4>

          <div class="page-title-right">
              <ol class="breadcrumb m-0">
                  <li class="breadcrumb-item"><a href="{% url 'income' %}">Kirim</a></li>
                  <li class="breadcrumb-item active">Barcha to'lovlar</li>
              </ol>
          </div>
      </div>
  </div>


<div class="row">
      <div class="col-12">
            <div  class=" card  col-12">
                  <div class="container" >
                        <br>
                  <form method="post"  >{% csrf_token %}
                          
                        <div class="row" >
                          <div class="col-5" >
                            <label for="example-date-input" class="form-label">Boshlanish</label>
                            <input class="form-control" name="start" type="date" value="{{start}}" id="example-date-input">
                          </div>
                          <div class="col-5" >
                            <label for="example-date-input" class="form-label">Tugash</label>
                            <input class="form-control" name="end" type="date" value="{{end}}" id="example-date-input">
                          </div>
                          <div class="col-2" ><button style='margin-top:27px' type="submit" class="btn btn-primary" >Submit</button></div>

                        </div>
                  
                     
                 
                      
                    </form>
                    <br>
                  </div>
                  
            </div>
          <div class="card">
              <div class="card-header">
                  <h4 class="card-title">Barcha to'lovlar</h4>
                  
              </div>
              <div class="card-body" style="overflow-x: auto;">
                  <table id="datatable-buttons" class="table table-bordered dt-responsive nowrap w-100">
                        <thead>
                          <tr>
                            <th scope="col">#</th>
                            <th scope="col">Ism, Familiya</th>
                            <th scope="col">Telefon raqam</th>
                            <th scope="col">To'lov summasi</th>
                            <th scope="col">Sana</th>
                            
                            
                          </tr>
                        </thead>
                        <tbody>
                              {% for i in payments %}
                          <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{i.student.full_name}}</td>
                            <td>{{i.student.phone_number}}</td>
                            <td>{{i.summ}}</td>
                            <td>{{i.date|date:"d.m.Y"}}</td>
                            
                          </tr>
                          {% endfor %}
                          
                        </tbody>
                  </table>    
              </div>


              
          </div>
          <!-- end cardaa -->
      </div> <!-- end col -->
  </div> <!-- end row -->

{% endblock content %}

templates/boss/all_salaries.html
{% extends 'boss/base.html' %}
{% block title %} Barcha ish haqi tarqatishlar {% endblock title %}

{% block content %}

<div class="col-12">
      <div class="page-title-box d-sm-flex align-items-center justify-content-between">
          <h4 class="mb-sm-0 font-size-18">Ish haqilar </h4>

          <div class="page-title-right">
              <ol class="breadcrumb m-0">
                  <li class="breadcrumb-item"><a href="{% url 'income' %}">Kirim</a></li>
                  <li class="breadcrumb-item active">Ish haqilar</li>
              </ol>
          </div>
      </div>
</div>

<div class="row">
  <div class="card col-12">
    <div class="container">
        <br>
        <form method="post" onsubmit="return validateForm()">{% csrf_token %}
            <div class="row">
                <div class="col-5">
                    <label for="start-date-input" class="form-label">Boshlanish</label>
                    <input class="form-control" name="start" type="date" value="{{start}}" id="start-date-input">
                </div>
                <div class="col-5">
                    <label for="end-date-input" class="form-label">Tugash</label>
                    <input class="form-control" name="end" type="date" value="{{end}}" id="end-date-input">
                </div>
                <div class="col-2">
                    <button style="margin-top:27px" type="submit" class="btn btn-primary">Yuborish</button>
                </div>
            </div>
        </form>
        <br>
    </div>
</div>

<script>
function validateForm() {
    const startDate = document.getElementById('start-date-input').value;
    const endDate = document.getElementById('end-date-input').value;

    if (!startDate && !endDate) {
        alert("Iltimos Boshlanish va Tugashni kiriting.");
        return false;
    } else if (!startDate) {
        alert("Iltimos Boshlanishni kiriting.");
        return false;
    } else if (!endDate) {
        alert("Iltimos Tugashni kiriting.");
        return false;
    }
    return true;
}
</script>

          <div class="card">
              <div class="card-header">
                  <h4 class="card-title">Barcha to'lovlar</h4>
                  
              </div>
              <div class="card-body" style="overflow-x: auto;">
                  <table id="datatable-buttons" class="table table-bordered dt-responsive nowrap w-100">
                        <thead>
                          <tr>
                              <th scope="col">#</th>
                              <th scope="col">Ism, Familiya</th>
                              <th scope="col">Telefon raqam</th>
                              <th scope="col">To'lov summasi</th>
                              <th scope="col">Sana</th>
                            
                          </tr>
                        </thead>
                        <tbody>
                              {% for i in salaries %}
                          <tr>
                              <th scope="row">{{ forloop.counter }}</th>
                              <td>{{i.teacher.first_name}} {{i.teacher.last_name}}</td>
                              <td>{{i.teacher.email}}</td>
                              <td>{{i.salary_summ}}</td>
                              <td>{{i.date}}</td>
                            
                          </tr>
                          {% endfor %}
                          
                        </tbody>
                  </table>    
              </div>


              
          </div>
          <!-- end cardaa -->
      </div> <!-- end col -->
  </div> <!-- end row -->

{% endblock content %}

templates/boss/create_course.html
{% extends 'boss/base.html' %}

{% block title %}
{% load static %}
Kurs ochish
{% endblock title %}
{% block content %}

<div class="container"><br>
    <h5>Kurs ochish</h5>
   
    {% if request.user.is_staff %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Yaratish</button>
        <a href="/" class="btn btn-danger">Ortga qaytish</a>

        <div id="div_id_name" class="form-group">
            <label for="id_name" class="requiredField">Nomi</label>
            <input type="text" name="name" class="form-control" required>
        </div>

        <div id="div_id_teacher" class="form-group">
            <label for="id_teacher" class="requiredField">O'qituvchi</label>
            <select name="teacher" class="form-select" required>
                {% for user in users %}
                <option value="{{ user.id }}">{{ user.username }}</option>
                {% endfor %}
            </select>
        </div>

        <div id="div_id_title" class="form-group">
            <label for="id_title" class="requiredField">Title</label>
            <input type="text" name="title" class="form-control" required>
        </div>

        <div id="div_id_price" class="form-group">
            <label for="id_price" class="requiredField">Narxi</label>
            <input type="number" name="price" class="form-control" required>
        </div>

        



        <div id="div_id_days" class="form-group">
            <label for="id_days" class="requiredField">Kunlar</label>
            <select name="days" class="form-select" required>
                {% for value, label in days %}
                <option value="{{ value }}">{{ label }}</option>
                {% endfor %}
            </select>
        </div>

        <div id="div_id_room" class="form-group">
            <label for="id_room" class="requiredField">Xona</label>
            <input type="number" name="room" class="form-control" required>
        </div>
       <div id="div_id_time" class="form-group">
            <label for="id_time" class="requiredField">Time</label>
            <input type="text" name="time" class="form-control" required>
        </div>
        <div class="form-group">
            <label for="student_search">O'quvchilarni izlash:</label>
            <input type="text" id="student_search" class="form-control" placeholder="O'quvchilarni qidiring...">
        </div>
       
        <div id="student_table" class="table-responsive">
            <table id="datatable-bordered" class="table table-bordered dt-responsive nowrap">
                <thead>
                    <tr>

                        <th scope="col" width="3%">Tanlash</th>
                        <th scope="col">Full Name</th>
                        <th scope="col">Telefon raqami</th>
                        
                    </tr>
                </thead>
                <tbody>
                    {% for student in students %}
                   

                    <tr>
                        <td>
                            <input class="form-check-input custom-checkbox"  type="checkbox" name="students" value="{{ student.id }}" id="student_{{ student.id }}" {% if student in form.instance.students.all %}checked{% endif %}>
                        </td>

                        <td>
                            <label class="form-check-label" for="student_{{ student.id }}">
                                {{ student.full_name }}
                            </label>
                        </td>


                        <td>{{ student.phone_number }}</td>
                        
                    </tr>
                   
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <br>
     
    </form>
    {% endif %}
</div>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const inputField = document.getElementById('student_search');
        const tableBody = document.querySelector('#datatable-bordered tbody');  // Updated selector
        const rows = tableBody.getElementsByTagName('tr');

        inputField.addEventListener('input', function() {
            const searchText = inputField.value.trim().toLowerCase();

            for (let row of rows) {
                const fullName = row.cells[1].textContent.toLowerCase();
                if (fullName.includes(searchText)) {
                    row.style.display = '';
                } else {
                    row.style.display = 'none';
                }
            }
        });
    });
</script>

{% endblock content %}

templates/boss/giving_salary.html
{% extends 'boss/base.html' %}
{% block title %}Oylik berish{% endblock title %}

{% block content %}
<style>
      .card{
            border:none;
            width: 70%;
      }
</style>
      <h5>Oylik berish</h5>
      <div style="padding: 10px;" class="card shadow  " >
            <h6  >
                  Teacher:
                  {{teacher.first_name}}
                  {{teacher.last_name}} |
                  Hisobida: {{teacher.wallet}} so'm |
                  Max: {{teacher.wallet}} so'm

            </h6>
            <h6>Forma</h6>
            <form method="post"> {% csrf_token %} 
            <div  class="mb-3">
                  <label for="exampleInputEmail1" class="form-label">Ish haqi miqdori (so'mda)</label>
                  <input required placeholder="2000000" max="{{teacher.wallet}}"  type="number" name="summ" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
            </div>
            <button type="submit" class="btn btn-primary" > Tasdiqlash </button>
            <a href="{% url 'index' %}" class="btn btn-danger" > Bekor qilish </a>
            </form>
      </div>

{% endblock content %}